name: Tests

on:
  workflow_call:

jobs:
  test:
    name: Test Configuration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Run tests via Makefile
      run: |
        make test
